### ISSUE TITLE
vglrun not installed 

### ISSUE THREAD

**Issue by qezlou** [ucr-hpcc/ucr-hpcc.github.io#62]
Hi,

[This part of the documentation](https://github.com/ucr-hpcc/ucr-hpcc.github.io/blob/master/content/en/Manuals/hpc_cluster/visual.md) is referencing to `vglrun` module which does not exist on the system. What is the most update way to run this ?

**Comment by jdhayes** [comment]
I was not aware that anyone even uses vglrun.
It was originally configured to support Amira and to run 3d graphics windows through xforwarding.
I dont think this would have good performance on a remote network. I can install this, but I have not tested it under the current environment. How do you plan to use this?

**Comment by qezlou** [comment]
I see, I was just exploring the ways I can use GPUs on hpcc to render my visualizations. I actually do not need the `vglrun`  and have never used it. So, I will close this issue and thank you for the explanation.
